[package]
name = "did_you_just_say_bot"
version = "0.1.0"
authors = ["atomicparade"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.7.1"
image = "0.23"
imageproc = "0.20"
log = "0.4"
regex = "1"
rusttype = "^0.8"
tempfile = "3.1"
serenity = "0.8"
